german_words = {
    'anbieten': ['offer'],
    'beantragen': ['apply for'],
    'bedauern': ['regret'],
    'beeinflussen': ['influence'],
    'begegnen': ['meet', 'encounter', 'come across'],
    'berichten': ['report'],
    'beschreiben': ['describe'],
    'besprechen': ['discuss'],
    'bestehen': ['pass'],
    'betrachten': ['consider'],
    'beweisen': ['prove'],
    'die Ausbildung': ['education'],
    'die Bewerbung': ['application'],
    'die Beziehung': ['relationship'],
    'die Entscheidung': ['decision'],
    'die Entwicklung': ['development'],
    'die Erfahrung': ['experience'],
    'die Forschung': ['research'],
    'die Fähigkeit': ['ability'],
    'die Gelegenheit': ['opportunity'],
    'die Gesellschaft': ['society'],
    'die Gesundheit': ['health'],
    'die Herausforderung': ['challenge'],
    'die Kenntnis': ['knowledge'],
    'die Leistung': ['performance', 'achievement', 'accomplishment'],
    'die Meinung': ['opinion'],
    'die Möglichkeit': ['possibility'],
    'die Nachricht': ['message'],
    'die Regierung': ['government'],
    'die Sicherheit': ['security'],
    'die Situation': ['situation'],
    'die Tätigkeit': ['activity'],
    'die Umgebung': ['surroundings'],
    'die Verantwortung': ['responsibility', 'duty', 'accountability', 'obligation'],
    'die Verbesserung': ['improvement'],
    'die Veränderung': ['change'],
    'die Voraussetzung': ['prerequisite'],
    'dienen': ['serve'],
    'entscheiden': ['decide', 'determine', 'choose'],
    'erklären': ['explain'],
    'erlauben': ['allow'],
    'ermöglichen': ['enable', 'allow', 'make possible', 'permit'],
    'erreichen': ['reach', 'achieve', 'attain'],
    'erwarten': ['expect'],
    'feststellen': ['determine'],
    'gehören': ['belong'],
    'gelingen': ['succeed'],
    'genießen': ['enjoy'],
    'gründen': ['found'],
    'handeln': ['act'],
    'hoffen': ['hope'],
    'kündigen': ['terminate'],
    'leisten': ['perform', 'provide', 'accomplish'],
    'lösen': ['solve'],
    'merken': ['notice'],
    'nutzen': ['use'],
    'prüfen': ['check'],
    'schaffen': ['manage'],
    'scheitern': ['fail'],
    'steigern': ['increase'],
    'teilnehmen': ['participate'],
    'unterstützen': ['support', 'assist', 'help'],
    'verbessern': ['improve'],
    'vergleichen': ['compare', 'contrast'],
    'verhindern': ['prevent'],
    'vermeiden': ['avoid', 'prevent', 'keep away from'],
    'vorbereiten': ['prepare'],
    'wählen': ['choose'],
    'zusammenfassen': ['summarize'],
    'die Absicht': ['intention', 'purpose', 'aim'],
'die Anerkennung': ['recognition', 'appreciation', 'acknowledgment'],
'die Anwendung': ['application', 'use'],
'die Anstrengung': ['effort', 'exertion'],
'die Aufmerksamkeit': ['attention', 'awareness'],
'die Bedingung': ['condition', 'requirement'],
'die Begeisterung': ['enthusiasm', 'excitement'],
'die Behörde': ['authority', 'government agency'],
'die Bedeutung': ['meaning', 'importance', 'significance'],
'die Beschäftigung': ['employment', 'occupation'],
'die Eigenschaft': ['characteristic', 'quality', 'trait'],
'die Einrichtung': ['facility', 'institution', 'establishment'],
'die Erinnerung': ['memory', 'recollection', 'reminder'],
'die Erwartung': ['expectation', 'anticipation'],
'die Gewohnheit': ['habit', 'custom'],
'die Maßnahme': ['measure', 'action', 'step'],
'die Pflicht': ['duty', 'obligation'],
'die Stimmung': ['mood', 'atmosphere'],
'die Unterstützung': ['support', 'assistance', 'help'],
'die Vereinbarung': ['agreement', 'arrangement'],
'die Wirkung': ['effect', 'impact'],
'die Zukunft': ['future'],
'abhängen': ['depend', 'be dependent'],
'anpassen': ['adapt', 'adjust'],
'bemerken': ['notice', 'observe'],
'betonen': ['emphasize', 'stress', 'highlight'],
'diskutieren': ['discuss', 'debate'],
'entdecken': ['discover', 'find'],
'gelten': ['apply', 'be valid', 'count as'],
'überzeugen': ['convince', 'persuade'],
'verzichten': ['do without', 'renounce', 'give up']
}
