german_words = {
    'anbieten': {'meanings': ['offer'], 'example_de': 'Ich möchte anbieten besser lernen.', 'example_en': "I would like to learn how to 'anbieten' better."},
    'beantragen': {'meanings': ['apply for'], 'example_de': 'Ich möchte beantragen besser lernen.', 'example_en': "I would like to learn how to 'beantragen' better."},
    'bedauern': {'meanings': ['regret'], 'example_de': 'Ich möchte bedauern besser lernen.', 'example_en': "I would like to learn how to 'bedauern' better."},
    'beeinflussen': {'meanings': ['influence'], 'example_de': 'Ich möchte beeinflussen besser lernen.', 'example_en': "I would like to learn how to 'beeinflussen' better."},
    'begegnen': {'meanings': ['meet', 'encounter', 'come across'], 'example_de': 'Ich möchte begegnen besser lernen.', 'example_en': "I would like to learn how to 'begegnen' better."},
    'berichten': {'meanings': ['report'], 'example_de': 'Ich möchte berichten besser lernen.', 'example_en': "I would like to learn how to 'berichten' better."},
    'beschreiben': {'meanings': ['describe'], 'example_de': 'Ich möchte beschreiben besser lernen.', 'example_en': "I would like to learn how to 'beschreiben' better."},
    'besprechen': {'meanings': ['discuss'], 'example_de': 'Ich möchte besprechen besser lernen.', 'example_en': "I would like to learn how to 'besprechen' better."},
    'bestehen': {'meanings': ['pass'], 'example_de': 'Ich möchte bestehen besser lernen.', 'example_en': "I would like to learn how to 'bestehen' better."},
    'betrachten': {'meanings': ['consider'], 'example_de': 'Ich möchte betrachten besser lernen.', 'example_en': "I would like to learn how to 'betrachten' better."},
    'beweisen': {'meanings': ['prove'], 'example_de': 'Ich möchte beweisen besser lernen.', 'example_en': "I would like to learn how to 'beweisen' better."},
    'die Ausbildung': {'meanings': ['education'], 'example_de': 'die Ausbildung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Ausbildung plays an important role in many situations.'},
    'die Bewerbung': {'meanings': ['application'], 'example_de': 'die Bewerbung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Bewerbung plays an important role in many situations.'},
    'die Beziehung': {'meanings': ['relationship'], 'example_de': 'die Beziehung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Beziehung plays an important role in many situations.'},
    'die Entscheidung': {'meanings': ['decision'], 'example_de': 'die Entscheidung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Entscheidung plays an important role in many situations.'},
    'die Entwicklung': {'meanings': ['development'], 'example_de': 'die Entwicklung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Entwicklung plays an important role in many situations.'},
    'die Erfahrung': {'meanings': ['experience'], 'example_de': 'die Erfahrung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Erfahrung plays an important role in many situations.'},
    'die Forschung': {'meanings': ['research'], 'example_de': 'die Forschung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Forschung plays an important role in many situations.'},
    'die Fähigkeit': {'meanings': ['ability'], 'example_de': 'die Fähigkeit spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Fähigkeit plays an important role in many situations.'},
    'die Gelegenheit': {'meanings': ['opportunity'], 'example_de': 'die Gelegenheit spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Gelegenheit plays an important role in many situations.'},
    'die Gesellschaft': {'meanings': ['society'], 'example_de': 'die Gesellschaft spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Gesellschaft plays an important role in many situations.'},
    'die Gesundheit': {'meanings': ['health'], 'example_de': 'die Gesundheit spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Gesundheit plays an important role in many situations.'},
    'die Herausforderung': {'meanings': ['challenge'], 'example_de': 'die Herausforderung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Herausforderung plays an important role in many situations.'},
    'die Kenntnis': {'meanings': ['knowledge'], 'example_de': 'die Kenntnis spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Kenntnis plays an important role in many situations.'},
    'die Leistung': {'meanings': ['performance', 'achievement', 'accomplishment'], 'example_de': 'die Leistung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Leistung plays an important role in many situations.'},
    'die Meinung': {'meanings': ['opinion'], 'example_de': 'die Meinung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Meinung plays an important role in many situations.'},
    'die Möglichkeit': {'meanings': ['possibility'], 'example_de': 'die Möglichkeit spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Möglichkeit plays an important role in many situations.'},
    'die Nachricht': {'meanings': ['message'], 'example_de': 'die Nachricht spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Nachricht plays an important role in many situations.'},
    'die Regierung': {'meanings': ['government'], 'example_de': 'die Regierung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Regierung plays an important role in many situations.'},
    'die Sicherheit': {'meanings': ['security'], 'example_de': 'die Sicherheit spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Sicherheit plays an important role in many situations.'},
    'die Situation': {'meanings': ['situation'], 'example_de': 'die Situation spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Situation plays an important role in many situations.'},
    'die Tätigkeit': {'meanings': ['activity'], 'example_de': 'die Tätigkeit spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Tätigkeit plays an important role in many situations.'},
    'die Umgebung': {'meanings': ['surroundings'], 'example_de': 'die Umgebung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Umgebung plays an important role in many situations.'},
    'die Verantwortung': {'meanings': ['responsibility', 'duty', 'accountability', 'obligation'], 'example_de': 'die Verantwortung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Verantwortung plays an important role in many situations.'},
    'die Verbesserung': {'meanings': ['improvement'], 'example_de': 'die Verbesserung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Verbesserung plays an important role in many situations.'},
    'die Veränderung': {'meanings': ['change'], 'example_de': 'die Veränderung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Veränderung plays an important role in many situations.'},
    'die Voraussetzung': {'meanings': ['prerequisite'], 'example_de': 'die Voraussetzung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Voraussetzung plays an important role in many situations.'},
    'dienen': {'meanings': ['serve'], 'example_de': 'Ich möchte dienen besser lernen.', 'example_en': "I would like to learn how to 'dienen' better."},
    'entscheiden': {'meanings': ['decide', 'determine', 'choose'], 'example_de': 'Ich möchte entscheiden besser lernen.', 'example_en': "I would like to learn how to 'entscheiden' better."},
    'erklären': {'meanings': ['explain'], 'example_de': 'Ich möchte erklären besser lernen.', 'example_en': "I would like to learn how to 'erklären' better."},
    'erlauben': {'meanings': ['allow'], 'example_de': 'Ich möchte erlauben besser lernen.', 'example_en': "I would like to learn how to 'erlauben' better."},
    'ermöglichen': {'meanings': ['enable', 'allow', 'make possible', 'permit'], 'example_de': 'Ich möchte ermöglichen besser lernen.', 'example_en': "I would like to learn how to 'ermöglichen' better."},
    'erreichen': {'meanings': ['reach', 'achieve', 'attain'], 'example_de': 'Ich möchte erreichen besser lernen.', 'example_en': "I would like to learn how to 'erreichen' better."},
    'erwarten': {'meanings': ['expect'], 'example_de': 'Ich möchte erwarten besser lernen.', 'example_en': "I would like to learn how to 'erwarten' better."},
    'feststellen': {'meanings': ['determine'], 'example_de': 'Ich möchte feststellen besser lernen.', 'example_en': "I would like to learn how to 'feststellen' better."},
    'gehören': {'meanings': ['belong'], 'example_de': 'Ich möchte gehören besser lernen.', 'example_en': "I would like to learn how to 'gehören' better."},
    'gelingen': {'meanings': ['succeed'], 'example_de': 'Ich möchte gelingen besser lernen.', 'example_en': "I would like to learn how to 'gelingen' better."},
    'genießen': {'meanings': ['enjoy'], 'example_de': 'Ich möchte genießen besser lernen.', 'example_en': "I would like to learn how to 'genießen' better."},
    'gründen': {'meanings': ['found'], 'example_de': 'Ich möchte gründen besser lernen.', 'example_en': "I would like to learn how to 'gründen' better."},
    'handeln': {'meanings': ['act'], 'example_de': 'Ich möchte handeln besser lernen.', 'example_en': "I would like to learn how to 'handeln' better."},
    'hoffen': {'meanings': ['hope'], 'example_de': 'Ich möchte hoffen besser lernen.', 'example_en': "I would like to learn how to 'hoffen' better."},
    'kündigen': {'meanings': ['terminate'], 'example_de': 'Ich möchte kündigen besser lernen.', 'example_en': "I would like to learn how to 'kündigen' better."},
    'leisten': {'meanings': ['perform', 'provide', 'accomplish'], 'example_de': 'Ich möchte leisten besser lernen.', 'example_en': "I would like to learn how to 'leisten' better."},
    'lösen': {'meanings': ['solve'], 'example_de': 'Ich möchte lösen besser lernen.', 'example_en': "I would like to learn how to 'lösen' better."},
    'merken': {'meanings': ['notice'], 'example_de': 'Ich möchte merken besser lernen.', 'example_en': "I would like to learn how to 'merken' better."},
    'nutzen': {'meanings': ['use'], 'example_de': 'Ich möchte nutzen besser lernen.', 'example_en': "I would like to learn how to 'nutzen' better."},
    'prüfen': {'meanings': ['check'], 'example_de': 'Ich möchte prüfen besser lernen.', 'example_en': "I would like to learn how to 'prüfen' better."},
    'schaffen': {'meanings': ['manage'], 'example_de': 'Ich möchte schaffen besser lernen.', 'example_en': "I would like to learn how to 'schaffen' better."},
    'scheitern': {'meanings': ['fail'], 'example_de': 'Ich möchte scheitern besser lernen.', 'example_en': "I would like to learn how to 'scheitern' better."},
    'steigern': {'meanings': ['increase'], 'example_de': 'Ich möchte steigern besser lernen.', 'example_en': "I would like to learn how to 'steigern' better."},
    'teilnehmen': {'meanings': ['participate'], 'example_de': 'Ich möchte teilnehmen besser lernen.', 'example_en': "I would like to learn how to 'teilnehmen' better."},
    'unterstützen': {'meanings': ['support', 'assist', 'help'], 'example_de': 'Ich möchte unterstützen besser lernen.', 'example_en': "I would like to learn how to 'unterstützen' better."},
    'verbessern': {'meanings': ['improve'], 'example_de': 'Ich möchte verbessern besser lernen.', 'example_en': "I would like to learn how to 'verbessern' better."},
    'vergleichen': {'meanings': ['compare', 'contrast'], 'example_de': 'Ich möchte vergleichen besser lernen.', 'example_en': "I would like to learn how to 'vergleichen' better."},
    'verhindern': {'meanings': ['prevent'], 'example_de': 'Ich möchte verhindern besser lernen.', 'example_en': "I would like to learn how to 'verhindern' better."},
    'vermeiden': {'meanings': ['avoid', 'prevent', 'keep away from'], 'example_de': 'Ich möchte vermeiden besser lernen.', 'example_en': "I would like to learn how to 'vermeiden' better."},
    'vorbereiten': {'meanings': ['prepare'], 'example_de': 'Ich möchte vorbereiten besser lernen.', 'example_en': "I would like to learn how to 'vorbereiten' better."},
    'wählen': {'meanings': ['choose'], 'example_de': 'Ich möchte wählen besser lernen.', 'example_en': "I would like to learn how to 'wählen' better."},
    'zusammenfassen': {'meanings': ['summarize'], 'example_de': 'Ich möchte zusammenfassen besser lernen.', 'example_en': "I would like to learn how to 'zusammenfassen' better."},
    'die Absicht': {'meanings': ['intention', 'purpose', 'aim'], 'example_de': 'die Absicht spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Absicht plays an important role in many situations.'},
    'die Anerkennung': {'meanings': ['recognition', 'appreciation', 'acknowledgment'], 'example_de': 'die Anerkennung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Anerkennung plays an important role in many situations.'},
    'die Anwendung': {'meanings': ['application', 'use'], 'example_de': 'die Anwendung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Anwendung plays an important role in many situations.'},
    'die Anstrengung': {'meanings': ['effort', 'exertion'], 'example_de': 'die Anstrengung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Anstrengung plays an important role in many situations.'},
    'die Aufmerksamkeit': {'meanings': ['attention', 'awareness'], 'example_de': 'die Aufmerksamkeit spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Aufmerksamkeit plays an important role in many situations.'},
    'die Bedingung': {'meanings': ['condition', 'requirement'], 'example_de': 'die Bedingung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Bedingung plays an important role in many situations.'},
    'die Begeisterung': {'meanings': ['enthusiasm', 'excitement'], 'example_de': 'die Begeisterung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Begeisterung plays an important role in many situations.'},
    'die Behörde': {'meanings': ['authority', 'government agency'], 'example_de': 'die Behörde spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Behörde plays an important role in many situations.'},
    'die Bedeutung': {'meanings': ['meaning', 'importance', 'significance'], 'example_de': 'die Bedeutung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Bedeutung plays an important role in many situations.'},
    'die Beschäftigung': {'meanings': ['employment', 'occupation'], 'example_de': 'die Beschäftigung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Beschäftigung plays an important role in many situations.'},
    'die Eigenschaft': {'meanings': ['characteristic', 'quality', 'trait'], 'example_de': 'die Eigenschaft spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Eigenschaft plays an important role in many situations.'},
    'die Einrichtung': {'meanings': ['facility', 'institution', 'establishment'], 'example_de': 'die Einrichtung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Einrichtung plays an important role in many situations.'},
    'die Erinnerung': {'meanings': ['memory', 'recollection', 'reminder'], 'example_de': 'die Erinnerung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Erinnerung plays an important role in many situations.'},
    'die Erwartung': {'meanings': ['expectation', 'anticipation'], 'example_de': 'die Erwartung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Erwartung plays an important role in many situations.'},
    'die Gewohnheit': {'meanings': ['habit', 'custom'], 'example_de': 'die Gewohnheit spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Gewohnheit plays an important role in many situations.'},
    'die Maßnahme': {'meanings': ['measure', 'action', 'step'], 'example_de': 'die Maßnahme spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Maßnahme plays an important role in many situations.'},
    'die Pflicht': {'meanings': ['duty', 'obligation'], 'example_de': 'die Pflicht spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Pflicht plays an important role in many situations.'},
    'die Stimmung': {'meanings': ['mood', 'atmosphere'], 'example_de': 'die Stimmung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Stimmung plays an important role in many situations.'},
    'die Unterstützung': {'meanings': ['support', 'assistance', 'help'], 'example_de': 'die Unterstützung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Unterstützung plays an important role in many situations.'},
    'die Vereinbarung': {'meanings': ['agreement', 'arrangement'], 'example_de': 'die Vereinbarung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Vereinbarung plays an important role in many situations.'},
    'die Wirkung': {'meanings': ['effect', 'impact'], 'example_de': 'die Wirkung spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Wirkung plays an important role in many situations.'},
    'die Zukunft': {'meanings': ['future'], 'example_de': 'die Zukunft spielt in vielen Situationen eine wichtige Rolle.', 'example_en': 'die Zukunft plays an important role in many situations.'},
    'abhängen': {'meanings': ['depend', 'be dependent'], 'example_de': 'Ich möchte abhängen besser lernen.', 'example_en': "I would like to learn how to 'abhängen' better."},
    'anpassen': {'meanings': ['adapt', 'adjust'], 'example_de': 'Ich möchte anpassen besser lernen.', 'example_en': "I would like to learn how to 'anpassen' better."},
    'bemerken': {'meanings': ['notice', 'observe'], 'example_de': 'Ich möchte bemerken besser lernen.', 'example_en': "I would like to learn how to 'bemerken' better."},
    'betonen': {'meanings': ['emphasize', 'stress', 'highlight'], 'example_de': 'Ich möchte betonen besser lernen.', 'example_en': "I would like to learn how to 'betonen' better."},
    'diskutieren': {'meanings': ['discuss', 'debate'], 'example_de': 'Ich möchte diskutieren besser lernen.', 'example_en': "I would like to learn how to 'diskutieren' better."},
    'entdecken': {'meanings': ['discover', 'find'], 'example_de': 'Ich möchte entdecken besser lernen.', 'example_en': "I would like to learn how to 'entdecken' better."},
    'gelten': {'meanings': ['apply', 'be valid', 'count as'], 'example_de': 'Ich möchte gelten besser lernen.', 'example_en': "I would like to learn how to 'gelten' better."},
    'überzeugen': {'meanings': ['convince', 'persuade'], 'example_de': 'Ich möchte überzeugen besser lernen.', 'example_en': "I would like to learn how to 'überzeugen' better."},
    'verzichten': {'meanings': ['do without', 'renounce', 'give up'], 'example_de': 'Ich möchte verzichten besser lernen.', 'example_en': "I would like to learn how to 'verzichten' better."},
    'ablehnen': {'meanings': ['reject', 'decline', 'refuse']},
    'abschließen': {'meanings': ['complete', 'finish', 'conclude']},
    'achten': {'meanings': ['respect', 'pay attention to']},
    'ändern': {'meanings': ['change', 'modify', 'alter']},
    'annehmen': {'meanings': ['accept', 'assume', 'take']},
    'antworten': {'meanings': ['answer', 'reply', 'respond']},
    'auswählen': {'meanings': ['select', 'choose']},
    'bearbeiten': {'meanings': ['edit', 'process', 'work on']},
    'behandeln': {'meanings': ['treat', 'handle', 'deal with']},
    'behalten': {'meanings': ['keep', 'retain']},
    'bekommen': {'meanings': ['receive', 'get']},
    'benötigen': {'meanings': ['need', 'require']},
    'berücksichtigen': {'meanings': ['consider', 'take into account']},
    'besitzen': {'meanings': ['own', 'possess']},
    'bestätigen': {'meanings': ['confirm', 'verify']},
    'bestimmen': {'meanings': ['determine', 'define']},
    'besuchen': {'meanings': ['visit', 'attend']},
    'beurteilen': {'meanings': ['assess', 'judge', 'evaluate']},
    'bevorzugen': {'meanings': ['prefer', 'favor']},
    'bilden': {'meanings': ['form', 'build', 'educate']},
    'durchführen': {'meanings': ['carry out', 'conduct', 'perform']},
    'empfehlen': {'meanings': ['recommend', 'suggest']},
    'enthalten': {'meanings': ['contain', 'include']},
    'entstehen': {'meanings': ['arise', 'develop', 'originate']},
    'entwickeln': {'meanings': ['develop']},
    'erfahren': {'meanings': ['experience', 'learn', 'find out']},
    'erfüllen': {'meanings': ['fulfill', 'meet', 'satisfy']},
    'erhalten': {'meanings': ['receive', 'obtain', 'maintain']},
    'erkennen': {'meanings': ['recognize', 'identify', 'realize']},
    'erleben': {'meanings': ['experience', 'live through']},
    'ersetzen': {'meanings': ['replace', 'substitute']},
    'ersparen': {'meanings': ['save', 'spare']},
    'erweitern': {'meanings': ['expand', 'extend']},
    'fordern': {'meanings': ['demand', 'require']},
    'fördern': {'meanings': ['promote', 'support', 'encourage']},
    'garantieren': {'meanings': ['guarantee', 'ensure']},
    'genügen': {'meanings': ['be sufficient', 'suffice']},
    'gestalten': {'meanings': ['shape', 'design', 'organize']},
    'gewinnen': {'meanings': ['win', 'gain']},
    'abhängen': {'meanings': ['depend on']},
    'informieren': {'meanings': ['inform', 'notify']},
    'kontrollieren': {'meanings': ['check', 'control', 'inspect']},
    'lächeln': {'meanings': ['smile']},
    'meinen': {'meanings': ['mean', 'think', 'believe']},
    'reagieren': {'meanings': ['react', 'respond']},
    'reduzieren': {'meanings': ['reduce', 'decrease']},
    'regeln': {'meanings': ['regulate', 'arrange']},
    'respektieren': {'meanings': ['respect']},
    'sammeln': {'meanings': ['collect', 'gather']},
    'schützen': {'meanings': ['protect']},
    'sichern': {'meanings': ['secure', 'ensure']},
    'sparen': {'meanings': ['save']},
    'stattfinden': {'meanings': ['take place', 'occur']},
    'stimmen': {'meanings': ['be correct', 'agree']},
    'tragen': {'meanings': ['carry', 'wear', 'bear']},
    'übernehmen': {'meanings': ['take over', 'assume']},
    'überprüfen': {'meanings': ['check', 'verify', 'inspect']},
    'überraschen': {'meanings': ['surprise']},
    'umfassen': {'meanings': ['include', 'comprise']},
    'umgehen': {'meanings': ['deal with', 'avoid']},
    'umsetzen': {'meanings': ['implement', 'carry out']},
    'unterscheiden': {'meanings': ['distinguish', 'differentiate']},
    'unterschreiben': {'meanings': ['sign']},
    'verbinden': {'meanings': ['connect', 'link']},
    'verbrauchen': {'meanings': ['consume', 'use up']},
    'verdienen': {'meanings': ['earn', 'deserve']},
    'verlangen': {'meanings': ['demand', 'request']},
    'verlassen': {'meanings': ['leave', 'abandon']},
    'verlieren': {'meanings': ['lose']},
    'vermitteln': {'meanings': ['mediate', 'convey']},
    'versprechen': {'meanings': ['promise']},
    'verstehen': {'meanings': ['understand']},
    'vertreten': {'meanings': ['represent']},
    'verursachen': {'meanings': ['cause']},
    'vorstellen': {'meanings': ['introduce', 'imagine', 'present']},
    'wachsen': {'meanings': ['grow']},
    'warnen': {'meanings': ['warn']},
    'werben': {'meanings': ['advertise', 'recruit']},
    'wissen': {'meanings': ['know']},
    'ziehen': {'meanings': ['pull', 'move', 'draw']},
    'das Angebot': {'meanings': ['offer', 'proposal']},
    'das Verhalten': {'meanings': ['behavior', 'conduct']},
    'das Ergebnis': {'meanings': ['result', 'outcome']},
    'das Ereignis': {'meanings': ['event', 'incident']},
    'das Einkommen': {'meanings': ['income', 'earnings']},
    'das Interesse': {'meanings': ['interest']},
    'das Mitglied': {'meanings': ['member']},
    'das Netzwerk': {'meanings': ['network']},
    'das Unternehmen': {'meanings': ['company', 'enterprise']},
    'das Verständnis': {'meanings': ['understanding', 'comprehension']},
    'das Verhalten': {'meanings': ['behavior', 'conduct']},
    'das Ziel': {'meanings': ['goal', 'target', 'objective']},
    'das Zeichen': {'meanings': ['sign', 'symbol', 'mark']},
    'die Entscheidungshilfe': {'meanings': ['decision aid']},
    'die Forschungsergebnisse': {'meanings': ['research findings']},
    'die Führung': {'meanings': ['leadership', 'management']},
    'die Grundlage': {'meanings': ['basis', 'foundation']},
    'die Industrie': {'meanings': ['industry']},
    'die Kommunikation': {'meanings': ['communication']},
    'die Kultur': {'meanings': ['culture']},
    'die Lösung': {'meanings': ['solution']},
    'die Produktion': {'meanings': ['production']},
    'die Qualität': {'meanings': ['quality']},
    'die Ressource': {'meanings': ['resource']},
    'die Strategie': {'meanings': ['strategy']},
    'die Technologie': {'meanings': ['technology']},
    'die Umwelt': {'meanings': ['environment']},
    'die Ursache': {'meanings': ['cause', 'reason']},
    'die Verwaltung': {'meanings': ['administration', 'management']},
    'die Voraussetzung': {'meanings': ['requirement', 'prerequisite']},
    'die Wirtschaft': {'meanings': ['economy', 'economics']},
    'die Zusammenarbeit': {'meanings': ['cooperation', 'collaboration']}
}
