german_words = {
    "die Herausforderung": "challenge",
    "die Voraussetzung": "prerequisite",
    "die Fähigkeit": "ability",
    "die Entscheidung": "decision",
    "die Verantwortung": "responsibility",
    "die Entwicklung": "development",
    "die Gelegenheit": "opportunity",
    "die Erfahrung": "experience",
    "die Umgebung": "surroundings",
    "die Verbesserung": "improvement",
    "vermeiden": "avoid",
    "beeinflussen": "influence",
    "erreichen": "achieve",
    "unterstützen": "support",
    "vergleichen": "compare",
    "teilnehmen": "participate",
    "ermöglichen": "enable",
    "betrachten": "consider",
    "beschreiben": "describe",
    "entscheiden": "decide",
    "die Beziehung": "relationship",
    "die Ausbildung": "education",
    "die Bewerbung": "application",
    "die Forschung": "research",
    "die Gesellschaft": "society",
    "die Gesundheit": "health",
    "die Kenntnis": "knowledge",
    "die Leistung": "performance",
    "die Meinung": "opinion",
    "die Möglichkeit": "possibility",
    "die Nachricht": "message",
    "die Regierung": "government",
    "die Sicherheit": "security",
    "die Situation": "situation",
    "die Tätigkeit": "activity",
    "die Veränderung": "change",
    "anbieten": "offer",
    "beantragen": "apply for",
    "bedauern": "regret",
    "begegnen": "encounter",
    "berichten": "report",
    "besprechen": "discuss",
    "bestehen": "pass",
    "beweisen": "prove",
    "dienen": "serve",
    "erklären": "explain",
    "erlauben": "allow",
    "erwarten": "expect",
    "feststellen": "determine",
    "gehören": "belong",
    "gelingen": "succeed",
    "genießen": "enjoy",
    "gründen": "found",
    "handeln": "act",
    "hoffen": "hope",
    "kündigen": "terminate",
    "leisten": "perform",
    "lösen": "solve",
    "merken": "notice",
    "nutzen": "use",
    "prüfen": "check",
    "schaffen": "manage",
    "scheitern": "fail",
    "steigern": "increase",
    "verbessern": "improve",
    "verhindern": "prevent",
    "vorbereiten": "prepare",
    "wählen": "choose",
    "zusammenfassen": "summarize",
    "die Herausforderung (1)": "challenge",
    "die Voraussetzung (1)": "prerequisite",
    "die Fähigkeit (1)": "ability",
    "die Entscheidung (1)": "decision",
    "die Verantwortung (1)": "responsibility",
    "die Entwicklung (1)": "development",
    "die Gelegenheit (1)": "opportunity",
    "die Erfahrung (1)": "experience",
    "die Umgebung (1)": "surroundings",
    "die Verbesserung (1)": "improvement",
    "vermeiden (1)": "avoid",
    "beeinflussen (1)": "influence",
    "erreichen (1)": "achieve",
    "unterstützen (1)": "support",
    "vergleichen (1)": "compare",
    "teilnehmen (1)": "participate",
    "ermöglichen (1)": "enable",
    "betrachten (1)": "consider",
    "beschreiben (1)": "describe",
    "entscheiden (1)": "decide",
    "die Beziehung (1)": "relationship",
    "die Ausbildung (1)": "education",
    "die Bewerbung (1)": "application",
    "die Forschung (1)": "research",
    "die Gesellschaft (1)": "society",
    "die Gesundheit (1)": "health",
    "die Kenntnis (1)": "knowledge",
    "die Leistung (1)": "performance",
    "die Meinung (1)": "opinion",
    "die Möglichkeit (1)": "possibility",
    "die Nachricht (1)": "message",
    "die Regierung (1)": "government",
    "die Sicherheit (1)": "security",
    "die Situation (1)": "situation",
    "die Tätigkeit (1)": "activity",
    "die Veränderung (1)": "change",
    "anbieten (1)": "offer",
    "beantragen (1)": "apply for",
    "bedauern (1)": "regret",
    "begegnen (1)": "encounter",
    "berichten (1)": "report",
    "besprechen (1)": "discuss",
    "bestehen (1)": "pass",
    "beweisen (1)": "prove",
    "dienen (1)": "serve",
    "erklären (1)": "explain",
    "erlauben (1)": "allow",
    "erwarten (1)": "expect",
    "feststellen (1)": "determine",
    "gehören (1)": "belong",
    "gelingen (1)": "succeed",
    "genießen (1)": "enjoy",
    "gründen (1)": "found",
    "handeln (1)": "act",
    "hoffen (1)": "hope",
    "kündigen (1)": "terminate",
    "leisten (1)": "perform",
    "lösen (1)": "solve",
    "merken (1)": "notice",
    "nutzen (1)": "use",
    "prüfen (1)": "check",
    "schaffen (1)": "manage",
    "scheitern (1)": "fail",
    "steigern (1)": "increase",
    "verbessern (1)": "improve",
    "verhindern (1)": "prevent",
    "vorbereiten (1)": "prepare",
    "wählen (1)": "choose",
    "zusammenfassen (1)": "summarize",
    "die Herausforderung (2)": "challenge",
    "die Voraussetzung (2)": "prerequisite",
    "die Fähigkeit (2)": "ability",
    "die Entscheidung (2)": "decision",
    "die Verantwortung (2)": "responsibility",
    "die Entwicklung (2)": "development",
    "die Gelegenheit (2)": "opportunity",
    "die Erfahrung (2)": "experience",
    "die Umgebung (2)": "surroundings",
    "die Verbesserung (2)": "improvement",
    "vermeiden (2)": "avoid",
    "beeinflussen (2)": "influence",
    "erreichen (2)": "achieve",
    "unterstützen (2)": "support",
    "vergleichen (2)": "compare",
    "teilnehmen (2)": "participate",
    "ermöglichen (2)": "enable",
    "betrachten (2)": "consider",
    "beschreiben (2)": "describe",
    "entscheiden (2)": "decide",
    "die Beziehung (2)": "relationship",
    "die Ausbildung (2)": "education",
    "die Bewerbung (2)": "application",
    "die Forschung (2)": "research",
    "die Gesellschaft (2)": "society",
    "die Gesundheit (2)": "health",
    "die Kenntnis (2)": "knowledge",
    "die Leistung (2)": "performance",
    "die Meinung (2)": "opinion",
    "die Möglichkeit (2)": "possibility",
    "die Nachricht (2)": "message",
    "die Regierung (2)": "government",
    "die Sicherheit (2)": "security",
    "die Situation (2)": "situation",
    "die Tätigkeit (2)": "activity",
    "die Veränderung (2)": "change",
    "anbieten (2)": "offer",
    "beantragen (2)": "apply for",
    "bedauern (2)": "regret",
    "begegnen (2)": "encounter",
    "berichten (2)": "report",
    "besprechen (2)": "discuss",
    "bestehen (2)": "pass",
    "beweisen (2)": "prove",
    "dienen (2)": "serve",
    "erklären (2)": "explain",
    "erlauben (2)": "allow",
    "erwarten (2)": "expect",
    "feststellen (2)": "determine",
    "gehören (2)": "belong",
    "gelingen (2)": "succeed",
    "genießen (2)": "enjoy",
    "gründen (2)": "found",
    "handeln (2)": "act",
    "hoffen (2)": "hope",
    "kündigen (2)": "terminate",
    "leisten (2)": "perform",
    "lösen (2)": "solve",
    "merken (2)": "notice",
    "nutzen (2)": "use",
    "prüfen (2)": "check",
    "schaffen (2)": "manage",
    "scheitern (2)": "fail",
    "steigern (2)": "increase",
    "verbessern (2)": "improve",
    "verhindern (2)": "prevent",
    "vorbereiten (2)": "prepare",
    "wählen (2)": "choose",
    "zusammenfassen (2)": "summarize",
    "die Herausforderung (3)": "challenge",
    "die Voraussetzung (3)": "prerequisite",
    "die Fähigkeit (3)": "ability",
    "die Entscheidung (3)": "decision",
    "die Verantwortung (3)": "responsibility",
    "die Entwicklung (3)": "development",
    "die Gelegenheit (3)": "opportunity",
    "die Erfahrung (3)": "experience",
    "die Umgebung (3)": "surroundings",
    "die Verbesserung (3)": "improvement",
    "vermeiden (3)": "avoid",
    "beeinflussen (3)": "influence",
    "erreichen (3)": "achieve",
    "unterstützen (3)": "support",
    "vergleichen (3)": "compare",
    "teilnehmen (3)": "participate",
    "ermöglichen (3)": "enable",
    "betrachten (3)": "consider",
    "beschreiben (3)": "describe",
    "entscheiden (3)": "decide",
    "die Beziehung (3)": "relationship",
    "die Ausbildung (3)": "education",
    "die Bewerbung (3)": "application",
    "die Forschung (3)": "research",
    "die Gesellschaft (3)": "society",
    "die Gesundheit (3)": "health",
    "die Kenntnis (3)": "knowledge",
    "die Leistung (3)": "performance",
    "die Meinung (3)": "opinion",
    "die Möglichkeit (3)": "possibility",
    "die Nachricht (3)": "message",
    "die Regierung (3)": "government",
    "die Sicherheit (3)": "security",
    "die Situation (3)": "situation",
    "die Tätigkeit (3)": "activity",
    "die Veränderung (3)": "change",
    "anbieten (3)": "offer",
    "beantragen (3)": "apply for",
    "bedauern (3)": "regret",
    "begegnen (3)": "encounter",
    "berichten (3)": "report",
    "besprechen (3)": "discuss",
    "bestehen (3)": "pass",
    "beweisen (3)": "prove",
    "dienen (3)": "serve",
    "erklären (3)": "explain",
    "erlauben (3)": "allow",
    "erwarten (3)": "expect",
    "feststellen (3)": "determine",
    "gehören (3)": "belong",
    "gelingen (3)": "succeed",
    "genießen (3)": "enjoy",
    "gründen (3)": "found",
    "handeln (3)": "act",
    "hoffen (3)": "hope",
    "kündigen (3)": "terminate",
    "leisten (3)": "perform",
    "lösen (3)": "solve",
    "merken (3)": "notice",
    "nutzen (3)": "use",
    "prüfen (3)": "check",
    "schaffen (3)": "manage",
    "scheitern (3)": "fail",
    "steigern (3)": "increase",
    "verbessern (3)": "improve",
    "verhindern (3)": "prevent",
    "vorbereiten (3)": "prepare",
    "wählen (3)": "choose",
    "zusammenfassen (3)": "summarize",
    "die Herausforderung (4)": "challenge",
    "die Voraussetzung (4)": "prerequisite",
    "die Fähigkeit (4)": "ability",
    "die Entscheidung (4)": "decision",
    "die Verantwortung (4)": "responsibility",
    "die Entwicklung (4)": "development",
    "die Gelegenheit (4)": "opportunity",
    "die Erfahrung (4)": "experience",
    "die Umgebung (4)": "surroundings",
    "die Verbesserung (4)": "improvement",
    "vermeiden (4)": "avoid",
    "beeinflussen (4)": "influence",
    "erreichen (4)": "achieve",
    "unterstützen (4)": "support",
    "vergleichen (4)": "compare",
    "teilnehmen (4)": "participate",
    "ermöglichen (4)": "enable",
    "betrachten (4)": "consider",
    "beschreiben (4)": "describe",
    "entscheiden (4)": "decide",
    "die Beziehung (4)": "relationship",
    "die Ausbildung (4)": "education",
    "die Bewerbung (4)": "application",
    "die Forschung (4)": "research",
    "die Gesellschaft (4)": "society",
    "die Gesundheit (4)": "health",
    "die Kenntnis (4)": "knowledge",
    "die Leistung (4)": "performance",
    "die Meinung (4)": "opinion",
    "die Möglichkeit (4)": "possibility",
    "die Nachricht (4)": "message",
    "die Regierung (4)": "government",
    "die Sicherheit (4)": "security",
    "die Situation (4)": "situation",
    "die Tätigkeit (4)": "activity",
    "die Veränderung (4)": "change",
    "anbieten (4)": "offer",
    "beantragen (4)": "apply for",
    "bedauern (4)": "regret",
    "begegnen (4)": "encounter",
    "berichten (4)": "report",
    "besprechen (4)": "discuss",
    "bestehen (4)": "pass",
    "beweisen (4)": "prove",
    "dienen (4)": "serve",
    "erklären (4)": "explain",
    "erlauben (4)": "allow",
    "erwarten (4)": "expect",
    "feststellen (4)": "determine",
    "gehören (4)": "belong",
    "gelingen (4)": "succeed",
    "genießen (4)": "enjoy",
    "gründen (4)": "found",
    "handeln (4)": "act",
    "hoffen (4)": "hope",
    "kündigen (4)": "terminate",
    "leisten (4)": "perform",
    "lösen (4)": "solve",
    "merken (4)": "notice",
    "nutzen (4)": "use",
    "prüfen (4)": "check",
    "schaffen (4)": "manage",
    "scheitern (4)": "fail",
    "steigern (4)": "increase",
    "verbessern (4)": "improve",
    "verhindern (4)": "prevent",
    "vorbereiten (4)": "prepare",
    "wählen (4)": "choose",
    "zusammenfassen (4)": "summarize",
    "die Herausforderung (5)": "challenge",
    "die Voraussetzung (5)": "prerequisite",
    "die Fähigkeit (5)": "ability",
    "die Entscheidung (5)": "decision",
    "die Verantwortung (5)": "responsibility",
    "die Entwicklung (5)": "development",
    "die Gelegenheit (5)": "opportunity",
    "die Erfahrung (5)": "experience",
    "die Umgebung (5)": "surroundings",
    "die Verbesserung (5)": "improvement",
    "vermeiden (5)": "avoid",
    "beeinflussen (5)": "influence",
    "erreichen (5)": "achieve",
    "unterstützen (5)": "support",
    "vergleichen (5)": "compare",
    "teilnehmen (5)": "participate",
    "ermöglichen (5)": "enable",
    "betrachten (5)": "consider",
    "beschreiben (5)": "describe",
    "entscheiden (5)": "decide",
    "die Beziehung (5)": "relationship",
    "die Ausbildung (5)": "education",
    "die Bewerbung (5)": "application",
    "die Forschung (5)": "research",
    "die Gesellschaft (5)": "society",
    "die Gesundheit (5)": "health",
    "die Kenntnis (5)": "knowledge",
    "die Leistung (5)": "performance",
    "die Meinung (5)": "opinion",
    "die Möglichkeit (5)": "possibility",
    "die Nachricht (5)": "message",
    "die Regierung (5)": "government",
    "die Sicherheit (5)": "security",
    "die Situation (5)": "situation",
    "die Tätigkeit (5)": "activity",
    "die Veränderung (5)": "change",
    "anbieten (5)": "offer",
    "beantragen (5)": "apply for",
    "bedauern (5)": "regret",
    "begegnen (5)": "encounter",
    "berichten (5)": "report",
    "besprechen (5)": "discuss",
    "bestehen (5)": "pass",
    "beweisen (5)": "prove",
    "dienen (5)": "serve",
    "erklären (5)": "explain",
    "erlauben (5)": "allow",
    "erwarten (5)": "expect",
    "feststellen (5)": "determine",
    "gehören (5)": "belong",
    "gelingen (5)": "succeed",
    "genießen (5)": "enjoy",
    "gründen (5)": "found",
    "handeln (5)": "act",
    "hoffen (5)": "hope",
    "kündigen (5)": "terminate",
    "leisten (5)": "perform",
    "lösen (5)": "solve",
    "merken (5)": "notice",
    "nutzen (5)": "use",
    "prüfen (5)": "check",
    "schaffen (5)": "manage",
    "scheitern (5)": "fail",
    "steigern (5)": "increase",
    "verbessern (5)": "improve",
    "verhindern (5)": "prevent",
    "vorbereiten (5)": "prepare",
    "wählen (5)": "choose",
    "zusammenfassen (5)": "summarize",
    "die Herausforderung (6)": "challenge",
    "die Voraussetzung (6)": "prerequisite",
    "die Fähigkeit (6)": "ability",
    "die Entscheidung (6)": "decision",
    "die Verantwortung (6)": "responsibility",
    "die Entwicklung (6)": "development",
    "die Gelegenheit (6)": "opportunity",
    "die Erfahrung (6)": "experience",
    "die Umgebung (6)": "surroundings",
    "die Verbesserung (6)": "improvement",
    "vermeiden (6)": "avoid",
    "beeinflussen (6)": "influence",
    "erreichen (6)": "achieve",
    "unterstützen (6)": "support",
    "vergleichen (6)": "compare",
    "teilnehmen (6)": "participate",
    "ermöglichen (6)": "enable",
    "betrachten (6)": "consider",
    "beschreiben (6)": "describe",
    "entscheiden (6)": "decide",
    "die Beziehung (6)": "relationship",
    "die Ausbildung (6)": "education",
    "die Bewerbung (6)": "application",
    "die Forschung (6)": "research",
    "die Gesellschaft (6)": "society",
    "die Gesundheit (6)": "health",
    "die Kenntnis (6)": "knowledge",
    "die Leistung (6)": "performance",
    "die Meinung (6)": "opinion",
    "die Möglichkeit (6)": "possibility",
    "die Nachricht (6)": "message",
    "die Regierung (6)": "government",
    "die Sicherheit (6)": "security",
    "die Situation (6)": "situation",
    "die Tätigkeit (6)": "activity",
    "die Veränderung (6)": "change",
    "anbieten (6)": "offer",
    "beantragen (6)": "apply for",
    "bedauern (6)": "regret",
    "begegnen (6)": "encounter",
    "berichten (6)": "report",
    "besprechen (6)": "discuss",
    "bestehen (6)": "pass",
    "beweisen (6)": "prove",
    "dienen (6)": "serve",
    "erklären (6)": "explain",
    "erlauben (6)": "allow",
    "erwarten (6)": "expect",
    "feststellen (6)": "determine",
    "gehören (6)": "belong",
    "gelingen (6)": "succeed",
    "genießen (6)": "enjoy",
    "gründen (6)": "found",
    "handeln (6)": "act",
    "hoffen (6)": "hope",
    "kündigen (6)": "terminate",
    "leisten (6)": "perform",
    "lösen (6)": "solve",
    "merken (6)": "notice",
    "nutzen (6)": "use",
    "prüfen (6)": "check",
    "schaffen (6)": "manage",
    "scheitern (6)": "fail",
    "steigern (6)": "increase",
    "verbessern (6)": "improve",
    "verhindern (6)": "prevent",
    "vorbereiten (6)": "prepare",
    "wählen (6)": "choose",
    "zusammenfassen (6)": "summarize",
    "die Herausforderung (7)": "challenge",
    "die Voraussetzung (7)": "prerequisite",
    "die Fähigkeit (7)": "ability",
    "die Entscheidung (7)": "decision",
    "die Verantwortung (7)": "responsibility",
    "die Entwicklung (7)": "development",
    "die Gelegenheit (7)": "opportunity",
    "die Erfahrung (7)": "experience",
    "die Umgebung (7)": "surroundings",
    "die Verbesserung (7)": "improvement",
    "vermeiden (7)": "avoid",
    "beeinflussen (7)": "influence",
    "erreichen (7)": "achieve",
    "unterstützen (7)": "support",
    "vergleichen (7)": "compare",
    "teilnehmen (7)": "participate",
    "ermöglichen (7)": "enable",
}
